<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\EclipsVault.Core\EclipsVault.Core.csproj" />
    <ProjectReference Include="..\EclipsVault.Infrastructure\EclipsVault.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QRCoder" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

</Project>
