namespace EclipsVault.Core.Application.Licensing;

/// <summary>
/// The vendor's license-signing PUBLIC key, pinned into the build. The app can only ever <em>verify</em>
/// with this; minting requires the matching private key, which the vendor keeps offline.
///
/// <para>
/// This is pinned at <b>build</b> time, which has a consequence worth stating: a licence verifies only
/// on a build whose pinned key matches the key it was signed with. Releases published before this
/// value was set (v1.0.0, v1.1.0) can never accept any licence, and rotating this key would invalidate
/// every licence already issued. It is set once and kept.
/// </para>
///
/// <para>
/// If it is ever empty again, every token verifies as InvalidSignature and the vault runs unlicensed —
/// soft, never blocking. That is the correct failure: an unconfigured vendor key is the vendor's
/// problem and must not become the operator's outage.
/// </para>
/// </summary>
public static class LicensePublicKey
{
    /// <summary>
    /// ECDSA P-256 SubjectPublicKeyInfo, base64. Generated by <c>LicenseForge keygen</c>.
    /// Rotated once, superseding the key shipped in v1.2.0; licences are issued against v1.3.0 onward.
    /// </summary>
    public const string VendorSpkiBase64 =
        "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEwxecNUdk4ZwRM4Fg8Nb/yRkoOMp86ksjzhuF5MJtfVpvAIumHVr81w40u5D7eU0BRuXhlNOMkBWJNprxQqVuag==";

    public static byte[] Spki =>
        string.IsNullOrEmpty(VendorSpkiBase64) ? [] : Convert.FromBase64String(VendorSpkiBase64);
}
